### ISSUE TITLE
Release a zip file and use grafana plugin installation

### ISSUE THREAD

**Issue by notz** [tiithansen/grafana-k8s-app#118]
Would not be easier to release a zip file in the release action like that:

```
      - name: Upload release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.PKG_TAG }} ./dist/*
``` 

and then we can use the zip in the helm chart like that:

```
grafana:
  plugins:
    - https://github.com/tiithansen/grafana-k8s-app/releases/download/v0.10.1/grafana-k8s-app-v0.10.1.zip;grafana-k8s-app
```
