### ISSUE TITLE
Network page is blank

### ISSUE THREAD

**Issue by bgatestmg** [tiithansen/grafana-k8s-app#121]
![Screenshot 2025-01-13 at 9 22 23 AM](https://github.com/user-attachments/assets/81b8f08b-bf74-43bd-a5d1-097b1d568153)
Network metrics page is blank.

RKE2 Cluster.

**Comment by tiithansen** [comment]
Hi, can you validate that you have following metrics available.

`kube_ingress_info`
`kube_ingress_path`
`kube_ingressclass_info`

These metrics are used to populate the list.

**Comment by bgatestmg** [comment]
Sorry for delay in response, those metrics are not available, makes sense why the data is empty now. I have switched to the k8s-monitoring v2 chart 

Here is my values what adjustments should i make?

```
cluster:
  name: tmg-rke2-prod

destinations:
  - name: prometheus
    type: prometheus
    url: https://mimir/api/v1/push
  - name: loki
    type: loki
    url: https://logs/loki/api/v1/push

integrations:
  cert-manager:
    instances:
      - name: cert-manager
        labelSelectors:
          app.kubernetes.io/name: cert-manager
  etcd:
    instances:
      - name: etcd
        labelSelectors:
          component: etcd

clusterMetrics:
  enabled: true
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
    enabled: true
  windows-exporter:
    deploy: false
    enabled: false
  kepler:
    enabled: true
  opencost:
    enabled: true
    metricsSource: prometheus
    opencost:
      exporter:
        defaultClusterId: tmg-rke2-prod
      prometheus:
        external:
          url: https://mimir

alloy-metrics:
  enabled: true
  alloy:
    stabilityLevel: public-preview
  remoteConfig:
    enabled: true
    url: "https://fleet-management-prod-008.grafana.net"
    auth:
      type: "basic"
      username: "redacted"
      password: "redacted"

clusterEvents:
  enabled: true

alloy-singleton:
  enabled: true

podLogs:
  enabled: true

alloy-logs:
  enabled: true

annotationAutodiscovery:
  enabled: true

autoInstrumentation:
  enabled: true
  beyla:
    enabled: true

prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
```

**Comment by tiithansen** [comment]
Under kube-state-metrics you need to modify the collectors property. Copy everything from [here](https://github.com/prometheus-community/helm-charts/blob/d854095927f902409f649bee9d57fc48d5d71d49/charts/kube-state-metrics/values.yaml#L363-L391) and add following also:

```
- ingresses
- ingressclasses
```

**Comment by bgatestmg** [comment]
i am using this helm chart to popualte kubernetes metrics: https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring

i will figure out the necessary additions and share with you

**Comment by tiithansen** [comment]
That chart uses kube-state-metrics chart as a dependency.

**Comment by strowi** [comment]
Thx for the hard work on this! ;)
It seems i am missing the `kube_ingressclass_info`-metric from kube-state-metrics on k3s-1.30. 
It's running with this:

```
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
    spec:
      containers:
      - args:
        - --port=8080
        - --resources=certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,leases,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments,ingressclasses
        image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.14
```

tried different version of kube-state-metrics, but so far no success... still testing though.
