### ISSUE TITLE
Provisioning possible?

### ISSUE THREAD

**Issue by strowi** [tiithansen/grafana-k8s-app#131]
Hi,

i was wondering if it is possible to provision this app like the rest of grafana?

regards,
strowi

**Comment by tiithansen** [comment]
Hi, what do you mean by that exactly?

**Comment by strowi** [comment]
basically putting the needed plugin-configuration (like default datasources, the various queries) in a file (in git) to autoconfigure everything. Similar how it works for dashoards and datasources ...[here](https://grafana.com/docs/grafana/latest/administration/provisioning/).

**Comment by tiithansen** [comment]
I have to test it, but I assume the `jsonData` field mentioned [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#example-plugin-configuration-file) is what is used to initialize plugin on startup. If so I will document the format as json schema.

**Comment by jcdauchy-moodys** [comment]
Here is any example of provisioning this app, it works and it is really nice to be able to customize the logs and events queries:                           
                                                                                                                                                            
```yaml                                                                                                                                                           
apiVersion: 1

apps:                                                                                                                                                       
  # K8s app plugin                                                                                                                                          
  - type: 'k8s-app'                                                                                                                                         
    org_id: < YOUR ORG ID>                                                                                                                                  
    org_name: < YOUR ORG NAME>                                                                                                                              
    disabled: false                                                                                                                                         
    jsonData:                                                                                                                                               
      analytics:                                                                                                                                            
        flatten: false                                                                                                                                      
        heartbeatAlways: true                                                                                                                               
        heartbeatInterval: 30                                                                                                                               
        postEnd: true                                                                                                                                       
        postHeartbeat: true                                                                                                                                 
        postStart: true                                                                                                                                     
        server: ""                                                                                                                                          
        showDetails: true                                                                                                                                   
      analyticsEnabled: false                                                                                                                               
      clusterFilter: ""                                                                                                                                     
      datasource: prometheus                                                                                                                                
      defaultCluster: cluster-test                                                                                                                          
      defaultDatasource: ""                                                                                                                                 
      eventQueries:                                                                                                                                         
        - datasource: "Pxxxxx"                                                                                                                   
          pageType: cluster                                                                                                                                 
          query: '{cluster="$$cluster", component="k8s-events"} | logfmt'                                                                                   
        - datasource: "Pxxxxx"                                                                                                                   
          pageType: node                                                                                                                                    
          query: '{cluster="$$cluster", component="k8s-events", source="Node"} | logfmt | object_name="$node"'                                              
        - datasource: "Pxxxxx"                                                                                                                   
          pageType: pod                                                                                                                                     
          query: '{cluster="$$cluster", component="k8s-events", source="Pod"} | logfmt | k8s_namespace=~"$$namespace" | object_name="$$pod"'                
        - datasource: "Pxxxxx"                                                                                                                   
          pageType: deployment                                                                                                                              
          query: '{cluster="$$cluster", component="k8s-events", source="Deployment"} | logfmt | k8s_namespace=~"$$namespace" | object_name="$$deployment"'  
        - datasource: "Pxxxxx"                                                                                                                   
          pageType: statefulset                                                                                                                             
          query: '{cluster="$$cluster", component="k8s-events", source="Statefulset"} | logfmt | k8s_namespace=~"$$namespace" | object_name="$$statefulset"'
        - datasource: "Pxxxxx"                                                                                                                   
          pageType: daemonset                                                                                                                               
          query: '{cluster="$$cluster", component="k8s-events", source="Daemonset"} | logfmt | k8s_namespace=~"$$namespace" | object_name="$$daemonset"'    
      logQueries:                                                                                                                                           
        - datasource: Pxxxxx                                                                                                                     
          pageType: cluster                                                                                                                                 
          query: '{cluster="$$cluster", component="k8s-containers"}'                                                                                        
        - datasource: Pxxxxx                                                                                                                     
          pageType: node                                                                                                                                    
          query: '{cluster="$$cluster", component="k8s-containers"} | logfmt | k8s_host=~"$$node"'                                                          
        - datasource: Pxxxxx                                                                                                                     
          pageType: pod                                                                                                                                     
          query: '{cluster="$$cluster", component="k8s-containers", k8s_namespace_name="$$namespace"} | logfmt | k8s_pod_name="$$pod"'                      
        - datasource: Pxxxxx                                                                                                                     
          pageType: deployment                                                                                                                              
          query: '{cluster="$$cluster", component="k8s-containers", k8s_namespace_name="$$namespace"}'                                                      
        - datasource: Pxxxxx                                                                                                                     
          pageType: statefulset                                                                                                                             
          query: '{cluster="$$cluster", component="k8s-containers", k8s_namespace_name="$$namespace"}'                                                      
        - datasource: Pxxxxx                                                                                                                     
          pageType: daemonset                                                                                                                               
          query: '{cluster="$$cluster", component="k8s-containers", k8s_namespace_name="$$namespace"}'                                                      
      logsEnabled: true                                                                                                                                     
      rulerMappings: []
```
